config/routes.rb
AmritaRecycleCenter::Application.routes.draw do
  devise_for :users
  resources :time_entries

  resources :tasks

  resources :transfer_line_items

  resources :containers

  resources :transfers

  resources :locations

  resources :categories
  
  resources :worksheets
  
  root to: 'transfers#index'
  
  get 'time_entries/by_date/:date' => 'time_entries#index', as: :time_entries_by_date
end

app/models/container.rb
class Container < ActiveRecord::Base
  validates :name, presence: true
  validates :empty_weight, numericality: true
  validates :capacity, numericality: true
  
  NO_CONTAINER_NAME = 'No Container (N/A)'
  def self.no_container
    find_by(name: NO_CONTAINER_NAME)
  end
  
  def display_name
    "#{name} (#{capacity}L/#{empty_weight}Kgs)"
  end
  
  extend FriendlyId  
  friendly_id :friendly_name, use: :slugged
  
  def friendly_name
    name.downcase.gsub(/[ -]/, '_') if name
  end
end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController
  before_action :set_container, only: [:show, :edit, :update, :destroy]

  def index
    @containers = Container.all
    respond_with(@containers)
  end

  def show
    respond_with(@container)
  end

  def new
    @container = Container.new
    respond_with(@container)
  end

  def edit
  end

  def create
    @container = Container.new(container_params)
    @container.save
    respond_with(@container)
  end

  def update
    @container.update(container_params)
    respond_with(@container)
  end

  def destroy
    @container.destroy
    respond_with(@container)
  end

  private
    def set_container
      @container = Container.friendly.find(params[:id])
    end

    def container_params
      params.require(:container).permit(:name, :capacity, :empty_weight)
    end
end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/views/containers/_form.html.slim
= form_for @container do |f|
  - if @container.errors.any?
    #error_explanation
      h2 = "#{pluralize(@container.errors.count, "error")} prohibited this container from being saved:"
      ul
        - @container.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :capacity
    = f.text_field :capacity
  .field
    = f.label :empty_weight
    = f.text_field :empty_weight
  .actions = f.submit 'Save'

app/views/containers/edit.html.slim
h1 Editing container

== render 'form'

= link_to 'Show', @container
'|
= link_to 'Back', containers_path

app/views/containers/index.html.slim
h1 Listing containers

table
  tr
    th Name
    th Capacity
    th Empty weight
    th
    th
    th

  - @containers.each do |container|
    tr
      td = container.name
      td = container.capacity
      td = container.empty_weight
      td = link_to 'Show', container
      td = link_to 'Edit', edit_container_path(container) if can? :manage, container
      td = link_to 'Destroy', container, data: {:confirm => 'Are you sure?'}, :method => :delete if can? :manage, container

br

= link_to 'New Container', new_container_path

app/views/containers/new.html.slim
h1 New container

== render 'form'

= link_to 'Back', containers_path

app/views/containers/show.html.slim
p#notice = notice

p
  strong Name:
  = @container.name
p
  strong Capacity:
  = @container.capacity
p
  strong Empty weight:
  = @container.empty_weight

= link_to 'Edit', edit_container_path(@container)
'|
= link_to 'Back', containers_path