config/routes.rb
AmritaRecycleCenter::Application.routes.draw do
  devise_for :users
  resources :time_entries

  resources :tasks

  resources :transfer_line_items

  resources :containers

  resources :transfers

  resources :locations

  resources :categories
  
  resources :worksheets
  
  root to: 'transfers#index'
  
  get 'time_entries/by_date/:date' => 'time_entries#index', as: :time_entries_by_date
end

app/models/transfer_line_item.rb
class TransferLineItem < ActiveRecord::Base
  belongs_to :category
  belongs_to :location
  belongs_to :container
  belongs_to :transfer
  
  before_validation :balance!, :truify_credit!
  
  validates :container, presence: true
  validates :gross_weight, numericality: true
  validates :net_weight, numericality: true
  
  validate :weight_should_only_be_negative_if_and_only_if_this_is_a_debit
  validate :net_weight_should_be_the_difference_between_gross_weight_and_container_weight
  
  def set_container_by_id(id)
    self.container = Container.friendly.find(id) if id
  end
  
  def set_location_by_id(id)
    self.location = Location.friendly.find(id) if id
  end
  
  def set_category_by_id(id)
    self.category = Category.friendly.find(id) if id
  end
  
  def weight_should_only_be_negative_if_and_only_if_this_is_a_debit
    return unless gross_weight
    if gross_weight > 0 && debit?
      errors.add(:gross_weight, "Must be negative for debit transactions.")
    elsif gross_weight < 0 && credit?
      errors.add(:gross_weight, "Must be positive for credit transactions.")
    end
  end
  
  def credit?
    !!credit
  end
  
  def debit?
    credit == false
  end
  
  def net_weight_should_be_the_difference_between_gross_weight_and_container_weight
    if container && net_weight && gross_weight
      unless net_weight.abs == (gross_weight.abs - container.empty_weight)
        errors.add(:net_weight, "Should be difference between gross weight and container weight")
      end
    end
  end
  
  def balance!
    unless container.nil? || gross_weight.nil? || gross_weight.abs < container.empty_weight
      self.net_weight = gross_weight >= 0 ? (gross_weight - container.empty_weight) : (gross_weight + container.empty_weight)
    end
  end
  
  def truify_credit!
    self.credit = true unless credit == false
  end
  
  def balance
    unless container.nil? || gross_weight.abs < container.empty_weight
      net_weight - (gross_weight >= 0 ? (gross_weight - container.empty_weight) : (gross_weight + container.empty_weight))
    end
  end
  
  private
  def net_weight=(weight)
    super
  end
end

app/controllers/transfer_line_items_controller.rb
class TransferLineItemsController < ApplicationController
  before_action :set_transfer_line_item, only: [:show, :edit, :update, :destroy]

  def index
    @transfer_line_items = TransferLineItem.all
    respond_with(@transfer_line_items)
  end

  def show
    respond_with(@transfer_line_item)
  end

  def new
    @transfer_line_item = TransferLineItem.new
    respond_with(@transfer_line_item)
  end

  def edit
  end

  def create
    @transfer_line_item = TransferLineItem.new(transfer_line_item_params)
    @transfer_line_item.save
    respond_with(@transfer_line_item)
  end

  def update
    @transfer_line_item.update(transfer_line_item_params)
    respond_with(@transfer_line_item)
  end

  def destroy
    @transfer_line_item.destroy
    respond_with(@transfer_line_item)
  end

  private
    def set_transfer_line_item
      @transfer_line_item = TransferLineItem.find(params[:id])
    end

    def transfer_line_item_params
      params.require(:transfer_line_item).permit(:credit, :account_id, :container_id, :gross_weight, :net_weight)
    end
end

app/helpers/transfer_line_items_helper.rb
module TransferLineItemsHelper
end

app/views/transfer_line_items/_form.html.slim
= form_for @transfer_line_item do |f|
  - if @transfer_line_item.errors.any?
    #error_explanation
      h2 = "#{pluralize(@transfer_line_item.errors.count, "error")} prohibited this transfer_line_item from being saved:"
      ul
        - @transfer_line_item.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :credit
    = f.check_box :credit
  .field
    = f.label :account
    = f.text_field :account
  .field
    = f.label :container
    = f.text_field :container
  .field
    = f.label :gross_weight
    = f.text_field :gross_weight
  .field
    = f.label :net_weight
    = f.text_field :net_weight
  .actions = f.submit 'Save'

app/views/transfer_line_items/edit.html.slim
h1 Editing transfer_line_item

== render 'form'

= link_to 'Show', @transfer_line_item
'|
= link_to 'Back', transfer_line_items_path

app/views/transfer_line_items/index.html.slim
h1 Listing transfer_line_items

table
  tr
    th Credit
    th Account
    th Container
    th Gross weight
    th Net weight
    th
    th
    th

  - @transfer_line_items.each do |transfer_line_item|
    tr
      td = transfer_line_item.credit
      td = transfer_line_item.account
      td = transfer_line_item.container
      td = transfer_line_item.gross_weight
      td = transfer_line_item.net_weight
      td = link_to 'Show', transfer_line_item
      td = link_to 'Edit', edit_transfer_line_item_path(transfer_line_item)
      td = link_to 'Destroy', transfer_line_item, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Transfer line item', new_transfer_line_item_path

app/views/transfer_line_items/new.html.slim
h1 New transfer_line_item

== render 'form'

= link_to 'Back', transfer_line_items_path

app/views/transfer_line_items/show.html.slim
p#notice = notice

p
  strong Credit:
  = @transfer_line_item.credit
p
  strong Account:
  = @transfer_line_item.account
p
  strong Container:
  = @transfer_line_item.container
p
  strong Gross weight:
  = @transfer_line_item.gross_weight
p
  strong Net weight:
  = @transfer_line_item.net_weight

= link_to 'Edit', edit_transfer_line_item_path(@transfer_line_item)
'|
= link_to 'Back', transfer_line_items_path