config/routes.rb
AmritaRecycleCenter::Application.routes.draw do
  devise_for :users
  resources :time_entries

  resources :tasks

  resources :transfer_line_items

  resources :containers

  resources :transfers

  resources :locations

  resources :categories
  
  resources :worksheets
  
  root to: 'transfers#index'
  
  get 'time_entries/by_date/:date' => 'time_entries#index', as: :time_entries_by_date
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true
  belongs_to :default_container, class_name: 'Container', foreign_key: 'default_container_id'
  
  validates :default_container, presence: true

  extend FriendlyId  
  friendly_id :friendly_name, use: :slugged
  
  def friendly_name
    name.downcase.gsub(/[ -]/, '_') if name
  end
  
  def default_container_friendly_id=(friendly_id)
    self.default_container = Container.friendly.find(friendly_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
    respond_with(@categories)
  end

  def show
    respond_with(@category)
  end

  def new
    @category = Category.new
    respond_with(@category)
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    @category.save
    respond_with(@category)
  end

  def update
    @category.update(category_params)
    respond_with(@category)
  end

  def destroy
    @category.destroy
    respond_with(@category)
  end

  private
    def set_category
      @category = Category.friendly.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.slim
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      h2 = "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      ul
        - @category.errors.full_messages.each do |message|
          li = message

  .row
    .small-6.columns
      = f.label :name
      = f.text_field :name
    .small-6.columns
      = f.collection_select :default_container_id, Container.all, :id, :name, {}, class: 'container'
  
  .actions = f.submit 'Save'

app/views/categories/edit.html.slim
h1 Editing category

== render 'form'

= link_to 'Show', @category
'|
= link_to 'Back', categories_path

app/views/categories/index.html.slim
h1 Listing categories

table
  tr
    th Name
    th
    th
    th

  - @categories.each do |category|
    tr
      td = category.name
      td = link_to 'Show', category
      td = link_to 'Edit', edit_category_path(category)
      td = link_to 'Destroy', category, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Category', new_category_path

app/views/categories/new.html.slim
h1 New category

== render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.slim
p#notice = notice

p
  strong Name:
  = @category.name

= link_to 'Edit', edit_category_path(@category)
'|
= link_to 'Back', categories_path