config/routes.rb
AmritaRecycleCenter::Application.routes.draw do
  devise_for :users
  resources :time_entries

  resources :tasks

  resources :transfer_line_items

  resources :containers

  resources :transfers

  resources :locations

  resources :categories
  
  resources :worksheets
  
  root to: 'transfers#index'
  
  get 'time_entries/by_date/:date' => 'time_entries#index', as: :time_entries_by_date
end

app/views/layouts/application.html.slim
doctype
/! paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/![if lt IE 7 ] <html class="ie6" lang="en">
/![if IE 7 ] <html class="ie7" lang="en">
/![if IE 8 ] <html class="ie8" lang="en">
/![if IE 9 ] <html class="ie9" lang="en">
/! [if (gt IE 9)|!(IE)]><!
html lang="en"
  /! <![endif]
  head
    meta charset="utf-8"
    /! Uncomment to make IE8 render like IE7
    /! <meta http-equiv="X-UA-Compatible" content="IE=7" />
    /! Set the viewport width to device width for mobile
    meta content="width=(device-width,)initial-scale=1.0" name="viewport"
    title= content_for?(:title) ? yield(:title) : "Amrita Recycle Center"
    = stylesheet_link_tag    "application"
    = csrf_meta_tags
  body
    nav.top-bar
      ul.title-area
        li.name
          h1
            = link_to "Amrita Recycle Center", root_path
      section.top-bar-section
        ul.right
          li.divider
          li= link_to "Delivery Worksheet", worksheet_path('delivery')
          li.divider
          li= link_to "New Blank Transfer", new_transfer_path
          li.divider
          li= link_to "Transfers", transfers_path
          li.divider
          li= link_to "Time Tracking", time_entries_path
          li.divider
          li
            a href="#" data-dropdown="data_settings_list"
              i.fi-widget
              = "Settings"
        ul#data_settings_list class="f-dropdown" data-dropdown-content="true"
          li= link_to "Task Types", tasks_path
          li= link_to "Waste Containers", containers_path
          li= link_to "Waste Categories", categories_path
          li= link_to "Locations", locations_path
    .row
      .small-9.columns= yield
      .small-3.columns
        h2.subheader Help
        | Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    = javascript_include_tag "application"
    = javascript_include_tag "vendor/custom.modernizr"
    